---
- hosts: localhost ansible_connection=local
  tasks:
  - name: update syslog
    command: echo "me"

  - command: hostnamectl set-hostname test.zeroglitch.org

  - name: import filebeats
    import_tasks: filebeat.yml
